# Copyright 2020 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-manager
  labels:
    app: participant-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participant-manager
  template:
    metadata:
      labels:
        app: participant-manager
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: participant-manager
          image: gcr.io/fda-mystudies-dev-apps/participant-manager:latest
          ports:
            - containerPort: 80
