apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-user-datastore
  labels:
    app: participant-user-datastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participant-user-datastore
  template:
    metadata:
      labels:
        app: participant-user-datastore
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: participant-user-datastore
          image: gcr.io/mystudies-dev-apps/participant-user-datastore:latest
          env:
            # DB ACCESS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: participant-user-datastore-credentials
                  key: dbusername
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: participant-user-datastore-credentials
                  key: dbpassword
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: participant-user-datastore-credentials
                  key: dbname
            # EMAIL SERVER
            - name: FROM_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_address
            - name: FROM_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_password
            - name: MAIL_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: from_email_address
            - name: MAIL_CONTACT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: contact_email_address
            - name: SMTP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: smtp_hostname
            - name: SMTP_USE_IP_ALLOWLIST
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: smtp_use_ip_allowlist
            - name: FROM_EMAIL_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: from_email_domain
            # AUTHENTICATION
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: participant-user-datastore-credentials
                  key: client_id
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: participant-user-datastore-credentials
                  key: secret_key
            # PUSH NOTIFICATIONS
            - name: FCM_API_URL
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: fcm_api_url
            - name: IOS_NOTIFICATION_TYPE
              value: "production"
            # SERVER CALLS
            - name: SCIM_AUTH_URL
              value: "http://auth-server-np:50000"
            - name: HYDRA_ADMIN_URL
              value: "http://hydra-np:4445"
            # MISC
            - name: ORG_NAME
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: org_name
            - name: LOG_PATH
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: log_path
            - name: INSTITUTION_RESOURCES_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: institution_resources_bucket_name
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/gcloud_key/key.json"
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /participant-user-datastore/healthCheck
              port: 8080
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command: ["/cloud_sql_proxy",
            "-instances=fda-mystudies-dev-data:us-east1:mystudies=tcp:3306",
            "-credential_file=/secrets/gcloud_key/key.json"]
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
      volumes:
      - name: gcloud-key-volume
        secret:
          secretName: participant-user-datastore-gcloud-key
