# TODO: Rename this from study-meta-data to study-server.
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: study-meta-data 
  labels: 
    app: study-meta-data 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: study-meta-data 
  template: 
    metadata: 
      labels: 
        app: study-meta-data 
    spec: 
      containers: 
        - name: study-meta-data 
          image: gcr.io/heroes-hat-dev/study-meta-data:latest
          env: 
            - name: DB_USER 
              valueFrom: 
                secretKeyRef: 
                  name: cloudsql-db-credentials 
                  key: username 
            - name: DB_PASS 
              valueFrom: 
                secretKeyRef: 
                  name: cloudsql-db-credentials 
                  key: password 
            - name: DB_NAME 
              valueFrom: 
                secretKeyRef: 
                  name: cloudsql-db-credentials 
                  key: dbname 
            - name: RESPONSE_SERVER
              value: "35.196.119.71:60000"
            - name: USER_REGISTRATION_SERVER
              value: "35.196.79.108:60000"
            - name: STUDY_DESIGNER
              value: "34.74.173.54:50000"
          ports:
          - containerPort: 8080
        - name: cloudsql-proxy 
          image: gcr.io/cloudsql-docker/gce-proxy:latest 
          command: ["/cloud_sql_proxy", 
            "-instances=heroes-hat-dev:us-east1:my-studies2=tcp:3306", 
            "-credential_file=/secrets/cloudsql/sql_credentials.json"] 
          volumeMounts: 
            - name: my-secrets-volume 
              mountPath: /secrets/cloudsql 
              readOnly: true 
      volumes: 
        - name: my-secrets-volume 
          secret: 
            secretName: cloudsql-instance-credentials
