# Copyright 2020 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: auth-server
        image: gcr.io/mystudies-dev-apps/auth-server:latest
        env:
        # DB ACCESS
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: auth-server-credentials
              key: dbusername
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: auth-server-credentials
              key: dbpassword
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: auth-server-credentials
              key: dbname
        # AUTHENTICATION
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: client-side-credentials
              key: client_id
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: client-side-credentials
              key: secret_key
        # MAIL SERVER
        - name: FROM_EMAIL_ADDRESS
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: email_address
        - name: FROM_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: email_password
        - name: SMTP_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: smtp_hostname
        - name: MAIL_CONTACT_EMAIL
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: contact_email_address
        - name: MAIL_FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: email-credentials
              key: from_email_address
        # SERVER CALLS
        - name: HYDRA_ADMIN_URL
          value: "http://hydra-admin-np:50000"
        - name: HYDRA_PUBLIC_URL
          value: "http://hydra-np:50000"
        - name: SCIM_AUTH_URL
          value: "http://auth-server-np:50000/oauth-scim-service"
        - name: BASE_URL
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: base_url
        - name: IOS_DEEPLINK_URL
          valueFrom:
            secretKeyRef:
              name: auth-server-secrets
              key: ios_deeplink_url
        - name: ANDROID_DEEPLINK_URL
          valueFrom:
            secretKeyRef:
              name: auth-server-secrets
              key: android_deeplink_url
        - name: ENCRYPTOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-server-secrets
              key: encryptor_password
        # MISC
        - name: LOG_PATH
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: log_path
        - name: TEMP_REGID_EXPIRY_MINUTES
          value: "30"
        - name: ORG_NAME
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: org_name
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/gcloud_key/key.json"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /oauth-scim-service/healthCheck
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 20
        volumeMounts:
        - name: gcloud-key-volume
          mountPath: /secrets/gcloud_key
          readOnly: true
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command: ["/cloud_sql_proxy",
                  "-instances=mystudies-dev-data:us-east1:mystudies=tcp:3306",
                  "-credential_file=/secrets/gcloud_key/key.json"]
        volumeMounts:
        - name: gcloud-key-volume
          mountPath: /secrets/gcloud_key
          readOnly: true
      volumes:
      - name: gcloud-key-volume
        secret:
          secretName: auth-server-gke-sa-gcloud-key
