# Copyright 2020 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <PREFIX>-<ENV>
  annotations:
    kubernetes.io/ingress.global-static-ip-name: <PREFIX>-<ENV>-ingress-ip
    networking.gke.io/managed-certificates: <PREFIX>-<ENV>-cert-participants,<PREFIX>-<ENV>-cert-studies
spec:
  rules:
    - host: participants.<PREFIX>-<ENV>.<DOMAIN>
      http:
        paths:
        - backend:
            service:          
              name: auth-server-np
              port: 
                number: 50000
           path: /auth-server/*
           pathType: ImplementationSpecific
         - backend:
             service:
              name: response-datastore-np
               port: 
                 number: 50000
            path: /response-datastore/*
            pathType: ImplementationSpecific
         - backend:
              service:
                name: participant-user-datastore-np
                port: 
                 number: 50000
            path: /participant-user-datastore/*
            pathType: ImplementationSpecific
         - backend:
              service:
               name: participant-consent-datastore-np
               port: 
                number: 50000
            path: /participant-consent-datastore/*
            pathType: ImplementationSpecific
         - backend:
              service:
              name: participant-enroll-datastore-np
              port: 
                number: 50000
            path: /participant-enroll-datastore/*
            pathType: ImplementationSpecific
          - backend:
              service:
              name: hydra-np
              port: 
               number: 50000
            path: /oauth2/*
            pathType: ImplementationSpecific
           - backend:
              service :
               name: participant-manager-np
               port: 
                number: 50000
            path: /participant-manager/*
            pathType: ImplementationSpecific
           - backend:
              service:
              name: participant-manager-datastore-np
              port: 
                number: 50000
            path: /participant-manager-datastore/*
            pathType: ImplementationSpecific
    - host: studies.<PREFIX>-<ENV>.<DOMAIN>
      http:
        paths:
           - backend:
              service:
               name: study-datastore-np
               port: 
                 number: 50000
            path: /study-datastore/*
            pathType: ImplementationSpecific
           - backend:
              service:
               name: study-builder-np
               port: 
                number: 50000
            path: /studybuilder/*
            pathType: ImplementationSpecific
           - backend:
              service:
               name: study-builder-np
               port: 
                 number: 50000
            path: /study-resources/*
            pathType: ImplementationSpecific
