# Copyright 2020 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-enroll-datastore
  labels:
    app: participant-enroll-datastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participant-enroll-datastore
  template:
    metadata:
      labels:
        app: participant-enroll-datastore
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: participant-enroll-datastore
          image: gcr.io/fda-mystudies-dev-apps/participant-enroll-datastore:latest
          env:
            # DB ACCESS
            - name: DB_INSTANCE_URL
              value: "127.0.0.1" 
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: participant-enroll-datastore-credentials
                  key: dbusername
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: participant-enroll-datastore-credentials
                  key: dbpassword
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: participant-enroll-datastore-credentials
                  key: dbname
            # AUTHENTICATION
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: participant-enroll-datastore-credentials
                  key: client_id
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: participant-enroll-datastore-credentials
                  key: secret_key
            # SERVER CALLS
            - name: HYDRA_ADMIN_URL
              value: "http://hydra-admin-np:50000"
            - name: RESPONSE_DATASTORE_URL
              value: "http://response-datastore-np:50000/response-datastore"
            - name: SCIM_AUTH_URL
              value: "http://auth-server-np:50000/auth-server"
            # MISC
            - name: LOG_PATH
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: log_path
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/gcloud_key/key.json"
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /participant-enroll-datastore/healthCheck
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 20
          resources:
            requests:
              memory: "400Mi"
              cpu: "50m"
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command: ["/cloud_sql_proxy",
            "-instances=fda-mystudies-dev-data:us-east1:mystudies=tcp:3306",
            "-credential_file=/secrets/gcloud_key/key.json"]
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
      volumes:
      - name: gcloud-key-volume
        secret:
          secretName: enroll-datastore-gke-sa-gcloud-key
