apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-ws
  labels:
    app: auth-server-ws
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: auth-server-ws
          image: gcr.io/fda-mystudies-dev-apps/auth-server-ws:latest
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-server-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-server-db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: auth-server-db-credentials
                  key: dbname
            - name: FROM_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_address
            - name: FROM_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_password
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/gcloud_key/key.json"
            - name: SMTP_HOSTNAME
              value: "smtp.gmail.com"
            - name: SMTP_USE_IP_WHITELIST
              value: "false"
            - name: FROM_EMAIL_DOMAIN
              value: ""
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /AuthServer/healthCheck
              port: 8080
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command: ['/cloud_sql_proxy', '-instances=fda-mystudies-dev-data:us-east1:mystudies=tcp:3306', '-credential_file=/secrets/gcloud_key/key.json']
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
      volumes:
      - name: gcloud-key-volume
        secret:
          secretName: auth-server-gcloud-key
