on:
  pull_request:
    paths:
    - 'WCP-WS/**'
    - '.github/workflows/build-studymetadata.yml'
name: Build studymetadata
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Build with Maven
      run: |
          cd WCP-WS
          mvn -B package --file pom.xml
