name: Build-iOS
on:
  pull_request:
    paths:
    - 'iOS/**'
    - '.github/workflows/build-iOS.yml'
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Force XCode 12.0
        run: sudo xcode-select -switch /Applications/Xcode_12.app
      - name: Build
        run: |
          cd iOS/HPHC
          xcodebuild clean build -workspace HPHC.xcworkspace -scheme HPHC -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
        env: 
         destination: ${{ matrix.destination }}
