name: Build-iOS
on:
  pull_request:
    paths:
    - 'iOS/**'
    - '.github/workflows/build-iOS.yml'
jobs:
  test:
    name: Build and test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.5,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Force XCode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Build
        run: |
          cd iOS/MyStudies
          xcodebuild clean build -workspace MyStudies.xcworkspace -scheme MyStudies -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          cd iOS/MyStudies
          xcodebuild test -workspace MyStudies.xcworkspace -scheme MyStudies -destination "${destination}"
        env: 
         destination: ${{ matrix.destination }}
