name: consent-mgmt-checkstyle

on:
  pull_request:
    paths:
    - 'user-registration-server-ws/consent-mgmt/**'
    - '.github/workflows/lint-consent-mgmt.yml'
jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /user-registration-server-ws/consent-mgmt
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        level: warning
        workdir: ./user-registration-server-ws/consent-mgmt/src
        tool_name: consent-mgmt Checks
