name: lint-oauth-scim

on:
  pull_request:
    paths:
    - 'oauth-scim-module/oauth-scim-service/**'
    - '.github/workflows/lint-oauth-scim-service.yml'
jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /oauth-scim-module/oauth-scim-service
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-review'
        level: error
        workdir: ./oauth-scim-module/oauth-scim-service
        tool_name: auth-server Checks
