name: lint-participant-consent-datastore

on:
  pull_request:
    paths:
    - 'participant-datastore/consent-mgmt-module/**'
    - '.github/workflows/lint-participant-consent-datastore.yml'
jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /participant-datastore/consent-mgmt-module/consent-mgmt
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-review'
        level: warning
        workdir: ./participant-datastore/consent-mgmt-module/consent-mgmt/src
        tool_name: consent-mgmt Checks
