name: lint-response-datastore

on:
  pull_request:
    paths:
    - 'response-datastore/response-server-service/**'
    - '.github/workflows/lint-response-datastore.yml'
jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /response-datastore/response-server-service
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-review'
        level: error
        workdir: ./response-datastore/response-server-service
        tool_name: response-server Checks
